lua/tpAtalas/core/colorscheme.lua
lua/tpAtalas/core/keymaps.lua
lua/tpAtalas/plugins-setup.lua
lua/tpAtalas/plugins/lualine.lua
lua/tpAtalas/plugins/toggle-term.lua

Added the new plugins: `colorizer` and `vim-visual-multi`. The `vim-visual-multi` helps select the exact word consecutively, while the `colorizer` helps to color the hex code.

Tp atalas/feature/setup plugins

---

lua/tpAtalas/core/keymaps.lua

Changed the keymap for the telescope as sequential keypress is not intuitive. Also, uncommented the markdown keymap.

refactor: Refactored the keymapping

---

lua/tpAtalas/core/keymaps.lua
lua/tpAtalas/plugins-setup.lua
lua/tpAtalas/plugins/lsp/lspconfig.lua

`typescript.nvim` plugin provides essential functionalities such as `removeUnusedVariables`, `applyFileChange`, etc.
refactor: Refactored the keymap

feat: Added the `typescript.nvim` plugins

---

lua/tpAtalas/core/keymaps.lua
lua/tpAtalas/plugins-setup.lua
lua/tpAtalas/plugins/lsp/lspconfig.lua

This reverts commit 0ec094a3b1fcb2ad52a1b2a59f9e30e19ead5da7.

Revert "feat: Added the `typescript.nvim` plugins (#21)"

---

README.md
lua/tpAtalas/core/keymaps.lua
lua/tpAtalas/plugins-setup.lua

Added the new plugin to improve the experience of creating markdown table.

feat: Added the new plugin: `vim-table-mode`

---

README.md
lua/tpAtalas/core/keymaps.lua

Added the basic keymaps as the table in README. More keymaps will be added in later update.

feat: Added the keymaps in README

---

lua/tpAtalas/core/options.lua
lua/tpAtalas/plugins/lsp/lspconfig.lua
lua/tpAtalas/plugins/lsp/null-ls.lua

Refactored the `prettier` within `null-ls`. Added the `foldcolumn` to show the icons properly. This is a terminal-dependent adjustment and useful only when the margin width is set to 0.

feat: Applied the minor changes

---

lua/tpAtalas/core/autocmd.lua
lua/tpAtalas/plugins/nvim-tree.lua
lua/tpAtalas/plugins/telescope.lua

refactored the layout of `telescope` for better UI and updated the setting for `nvim-tree`. Updated the auto-highlight autocmd to exclude the `nvim-tree`.

refactor: Refactored the plugins

---

lua/tpAtalas/core/colorscheme.lua
lua/tpAtalas/plugins/lualine.lua
lua/tpAtalas/plugins/nvim-cmp.lua
lua/tpAtalas/plugins/toggle-term.lua
lua/tpAtalas/plugins/treesitter.lua

Updated the lualine plugin with the new style of the status line. Minor changes on colorscheme. Now the cmp confirm is set to false as default.

refactor: Refactored the overall colorscheme and theme

---

lua/tpAtalas/core/autocmd.lua
lua/tpAtalas/core/options.lua
lua/tpAtalas/plugins/lsp/lspconfig.lua
lua/tpAtalas/plugins/nvim-cmp.lua

Minor performance improved by setting the following:
1. Debounce and throttle in nvim.cmp
2. Limit the total items to display in popup
3. Changes on auto-Save method

perf: Improved the performance

---

lua/tpAtalas/core/autocmd.lua
lua/tpAtalas/plugins/nvim-cmp.lua

Adjusted the `nvim-cmp` setting and refactored the auto-save and auto-highlight autocmd to improved the performance.

perf: Improved the general performance

---

lua/user/core/colorscheme.lua

Updated the color of colorColumn, CursorLineNr, CursorLine, and TelescopeBorder.

feat: Updated the highlight color

---

lua/user/plugins/telescope.lua

Added the the option to show the gitignore files in telescope_file_browser.

feat: Added the new option to the telescope_file_browser

---

README.md
lua/user/plugins-setup.lua
lua/user/plugins/lualine.lua

Removed the plugins: `impatient.nvim` and and `rest-nvim`.

refactor: Cleaned up the unused plugins

---

lua/user/core/autocmd.lua
lua/user/core/colorscheme.lua

Added the blink cursor in autocmd.

feat: Added the blink-cursor

---

lua/user/core/autocmd.lua
lua/user/core/colorscheme.lua
lua/user/plugins-setup.lua
lua/user/plugins/lualine.lua

Installed the Tokyonight colorScheme plugin and uninstalled the NightFox as it does not have good matching colors in transparent mode. The similar color palettes make things hard to distinguish.

feat: Implemented Tokyonight colorScheme

---

lua/user/core/colorscheme.lua
lua/user/core/keymaps.lua
lua/user/plugins/lsp/lspconfig.lua

Added the new keymaps to edit and force edit. Adjusted the minor colorsSchemes, and added the new language servers.
The new LSP: jsonls and esline

feat: Updated the minor settings

---

lua/user/plugins/lsp/lspconfig.lua
lua/user/plugins/lsp/null-ls.lua

Updated the settings for `lspconfig` to lively update the diagnostics. This may cause performance issues, and the `virtual_text` is disabled to reduce performance bottleneck.
Added the `cspell` diagnostics and codeactions to `null-ls`. Additionally, the custom file directory function for the `cspell.json` is added to integrate the dictionaries across multiple workspaces. This may increase i the usability; however, the performance may cause issues later.

feat: Updated the settings and added the `cspell` to `null-ls`

---

lua/user/plugins/telescope.lua
lua/user/plugins/toggle-term.lua

Resized the `toggleTerm` and `telescope` larger to equip them with the bigger font size. If the font size is not big enough, It is better to adjust to the smaller window size.

refactor: Resized the `toggleTerm` and `telescope`

---

lua/user/core/autocmd.lua
lua/user/core/keymaps.lua
lua/user/plugins/lsp/lspconfig.lua

Removed the lsp remap keys from `keymap`, and refactored the lspconfig with ltex-extra to work with keymaps. Rewrote the autcmd to auto reload `ltex-extra` plugin whenever the cursorHold is triggered.

refactor: Refactored the `lspconfig` with `ltex-extra`

---

lua/user/core/autocmd.lua
lua/user/plugins/lsp/lspconfig.lua

Added the `word2vec` to `ltex` to improve the language grammar/spell checking detection.
Other minor change: Removed the autocmd for reloading `ltex-extra` plugin

feat: Added the `word2vec` language model to `ltex`

---

lua/user/plugins/lsp/lspconfig.lua
lua/user/plugins/lsp/null-ls.lua
lua/user/plugins/lualine.lua

This reverts commit a73628ec11332b83e10a072445e620b87bd0066b.
feat: Removed the unused source from `lualine`

Revert "refactor: Refactored the diagnostics (#133)"

---

init.lua
lua/user/core/keymaps.lua
lua/user/plugins/lspsaga.lua

- Updated keymap to show the preview on finding strings
- Added the missing border from lspsaga
- Removed the frequency of checker from Lazy's config

feat: Updated the general configs

---

lazy-lock.json
lua/user/core/keymaps.lua
lua/user/core/options.lua
lua/user/plugins/colorscheme.lua
lua/user/plugins/comment.lua
lua/user/plugins/init.lua
lua/user/plugins/lspsaga.lua
lua/user/plugins/lualine.lua
lua/user/plugins/noice.lua

- feat: remove lazy loading option from commenting plugins
- refactor: remove the dead configs from lspsaga
- feat: add option shortmess
- feat: switch the vertical window resize
- refactor: refactor ltex and lsp on lualina
- refactor: refactor the keymap to delete all buffers except the current one
- feat: add new plugin: noice
- feat: add new highlight group to colorscheme
- feat: add silent to the writ keymap
- feat: update the command section fg and bg colors in lualine
- feat: update the cmdline in lualine
- feat: Update the config of noice
- feat: change the toggle key for commenting
- feat: switch the style to moon from night in colorScheme
- feat: add more option to shortmess

feat: update configs options

---

lua/user/plugins/lspconfig.lua
lua/user/plugins/lualine.lua

The some symbols/icons does not render the correct size. Switching to nerd font's symbol fixed the issue.

fix: fix the symbol rendering issue

---

lua/user/plugins/init.lua
lua/user/plugins/lspsaga.lua

fix the issue that markdown preview does not work with the custom browser.
Core changes:
- fix: fix the function to open alternative browser on markdown preview.
Misc changes:
- refactor: uncomment the event on Lspsaga.

fix: fix the markdown preview issue

---

init.lua
lua/user/plugins/init.lua

remove the plugin called `vim-hardtime`.

feat: remove the plugin

---

README.md

feat: add the examples and partially update the README.

docs: partially update README

---

README.md
lua/user/core/autocmd.lua

Update the core features section of the README to include more details. Remove text wrapping for markdown file types to improve readability.

feat: partially update the README

---

lua/user/core/keymaps.lua

Remove the keyamps related to spell checking and custom braket selection.

feat: remove the unused keymaps

---

lua/user/core/keymaps.lua

Update the following keymaps:
- Remap the up and down 5 lines
- Improve search current word under the cursor with case sensitive
- Add the kemap to find the bracket

feat: update the keymaps

---

lazy-lock.json
lua/user/plugins/colorscheme.lua
lua/user/plugins/init.lua
lua/user/plugins/null-ls.lua

Add the indent-balnkline.nvim plugin and adjut the colorScheme

feat: add the new plugin

---

lua/user/keymaps.lua

Add the character navigation keymaps to navigate with character forward and backward.

feat: add the character additional navigation keymaps

---

lazy-lock.json
lua/user/keymaps.lua

Optimize the Harpoon and default navigation keymaps by ensuring the cursor remains centered during navigation actions. This update enhances the user experience by providing a more intuitive and consistent view as users navigate through the code or interface.

refactor: Enhance keymap navigation

---

lua/user/plugins/null-ls.lua

Add `diagnostics.actionlint` to shows the diagnostics for the Github Actions.

feat: Update the null-ls configs

---

lua/user/plugins/nvim-cmp.lua

Set the auto-complete to true to use the auto-completion

feat: Update nvim-cmp configs

---

lua/user/keymaps.lua

Add new keymaps to Harpoon to remove and clear all the list.

feat: Add more keymaps for Harpoon

---

lua/user/plugins/init.lua

Update the Barbecue plugin by removing the unused option.

feat: Update the Barbecue plugin

---

lua/user/plugins/colorscheme.lua

Update the colorscheme variation to `Nightfox` from `Nordfox`.

feat: Update the colorscheme of Nightfox

---

lua/user/plugins/colorscheme.lua

Add the following highlight group with white `fg`:
- TelescopeBorder
- VertSplit

feat: Add the new highlight groups

---

lua/user/plugins/colorscheme.lua
lua/user/plugins/neo-tree.lua

The Neo-tree underwent an optimization for display by resizing its width.
Furthermore, enhanced functionality with new highlight groups and a configuration
update for Neo-tree has been implemented.
- feat: Add the new highlight groups (#285)
- feat: Update the neo-tree configuration (#284)
- refactor: Resize the width of the Neo-tree (#286)

chore(merge): Resize and Highlight Updates in Neo-tree

---

lua/user/plugins/colorscheme.lua

Remove the italic font option from the comment on the the colorscheme.

refactor: Update the colorscheme

---

lua/plugins/neotest.lua

Neotest plugin implementation aims at enhancing testing environment. Anticipated result is a significant reduction in test operation time. Please note that this does not improve the performance of the test runner.

feat: Implement Neotest plugin

---

lua/plugins/lualine.lua

Add filetype to Lualine and reorganize sections for improved layout. No functional changes made.

refactor: Update Lualine plugin configuration

---

lua/keymaps.lua

Incorporated navigation keymaps for vertical movement, enabling advancement by 5 lines utilizing the control and arrow keys. Ensures enhanced ease in precise vertical navigation.

feat: Implement new navigation keymaps

---

lua/keymaps.lua

Remove the unused keymaps, and add the new keymaps to move the current line under the cursor.

refactor: Update the keymaps

---

lua/keymaps.lua

Add the new keymaps that are already existing before, but they are added to improve the navigation experiences.
- Add the pageDown and pageUp keymap to move 7 lines up/down.
- Add + and - now jump back to older/newer position.
- Add End key to redo the changes.

feat: Add the new keymaps

---

lua/plugins/colorscheme.lua
lua/plugins/harpoon.lua
lua/plugins/lualine.lua

Integrate Harpoon's tabline and navigation keymaps utilizing file number. Modify Harpoon and lualine colorscheme for consistency.

refactor: Enhance Harpoon configurations

---

lua/lazy.lua

Remove the border and update the inline commment.

refactor: Adjust the UI of the Lazy plugin

---

lua/plugins/colorscheme/init.lua
lua/plugins/nvim_cmp/configs.lua

Add the cmp border and other floating borders. Update the highlight groups.

refactor: Update colorscheme and cmp borders

---

lua/plugins/lspconfig/servers.lua

Add the autocompletion inside cva within the lsp of the tailwind.

feat: Add the cva auto-completion to tailwind lsp

---

lua/plugins/autopairs/init.lua
lua/plugins/comment/init.lua
lua/plugins/gitsigns/init.lua
lua/plugins/harpoon/init.lua
lua/plugins/init.lua
lua/plugins/lualine/init.lua
lua/plugins/neotest/init.lua
lua/plugins/oil/init.lua
lua/plugins/toggle_term/init.lua
lua/plugins/tw_values/init.lua
lua/plugins/typescript_tools/init.lua

Apply 'VeryLazy' or 'lazy=true' to suitable plugin to enhance initial loading time.

refactor: Optimize initial loading time

---

lua/plugins/colorscheme/init.lua
lua/plugins/flash/init.lua

Update the Flash configs by disabling the option `char`, and higlight group for the FlashLabel has been updated from the colorscheme.

refactor: Update the Flash configs

---

lua/plugins/lualine/custom_components.lua
lua/plugins/lualine/init.lua

Add the new custom component that renders the files name of the cwd. This is useful to show the root directory of the project.

feat: Add the new custom_components to lualine

---

lua/autocmd.lua

Add the autocmd to clear history jumps before entering into neovim.

feat: Add the new autocmd

---

lua/plugins/lualine/custom_components.lua
lua/plugins/lualine/init.lua

Introduce a custom_component in lualine for returning the paths of the current directory.

feat: Add custom_component: path_winbar

---

lua/plugins/toggle_term/init.lua

Fix the issue that ToggleTerm does not render correctly for Lazygit whenever the Next.js's group directory is used.

fix: Fix the issue of ToggleTerm and Lazygit

---

lua/plugins/toggle_term/init.lua

Remove and update the unncessary settings.

refactor: Refine the ToggleTerm's settings

---

lua/plugins/lualine/init.lua

Update some font icons in lualine to render correctly in some terminal emulator such as Alacritty.

feat: Update some icons in lualine

---

lua/plugins/tsc/autocmd.lua
lua/plugins/tsc/init.lua

Now TSC plugins runs the typechecking automatically with debounce.

feat: Add the autocmd to TSC plugin

---

lua/plugins/lualine/custom_components.lua
lua/plugins/lualine/init.lua

Add the custom_component to show the number of quickfix items.

feat: Add the custom_component in lualine

---

lua/plugins/lspconfig/init.lua
lua/plugins/lspconfig/servers.lua
lua/plugins/lspconfig/utils.lua

Integrate tsserver into lspconfig, enhancing it with utility functions for 'add missing imports' and 'remove unused imports'. This integration streamlines development workflows and improves code management.

feat: Integrate tsserver in lspconfig with utils

---

lua/configs/colorscheme.lua
lua/plugins/colorscheme/init.lua
lua/plugins/colorscheme/mapping.lua
lua/plugins/colorscheme/setup.lua
lua/plugins/lualine/init.lua

Improve the colorscheme setup to easily maintain the predefined colorscheme.

refactor: Refactor the colorscheme setup

---

lua/plugins/conform/init.lua

feat: Add the new formatter

---

lua/autocmd/highlight_match.lua

Enhance the auto-highlight functionality in autocmd, optimizing the highlighting and clearing process of words under the cursor. This update introduces an optional delay timer for better performance.

refactor: Enhance auto-highlight efficiency

---

lua/plugins/lualine/custom_components.lua
lua/plugins/lualine/init.lua

Now custom component, winbar, of lualine, shows the current working directory as well.

feat: Introduce new feature to custom component

---

lua/keymaps.lua

Enhanced navigation in markdown, especially within code blocks, with new keymaps.

feat: Add keymaps for markdown navigation
