tpatalas/tp-neovim-config

.gitignore
lua/tpAtalas/core/autocmd.lua
lua/tpAtalas/core/keymaps.lua
lua/tpAtalas/core/options.lua
lua/tpAtalas/plugins-setup.lua

Added the better keymap for the jump through word and pargraph. To achieve this the default setup for the plugin `visual-multi` must be disabled due to its conflict.
New autocmd is added to limit the textwidth for the markdown files only.

refactor: Improved the keymap for the navigation

---

lua/tpAtalas/core/options.lua
lua/tpAtalas/plugins/lualine.lua

`lualine` now supports the 0 height of `cmdheight`.

refactor: Removed the `cmdheight` for the `lualine`

---

README.md
lua/tpAtalas/core/keymaps.lua
lua/tpAtalas/plugins/lsp/lspconfig.lua
lua/tpAtalas/plugins/lsp/null-ls.lua
lua/tpAtalas/plugins/lualine.lua
lua/tpAtalas/plugins/trouble.lua

Because of the nature of language servers, the diagnostics have not been triggered at the workspace level but only at the local level. The diagnostics are only triggered if the buffer/file is open.
Parsing diagnostics from the Typescript compiler, `tsc`, within `null-ls` fixed this issue.

fix: Fixed the diagnostics not triggered in the workspace level

---

lua/tpAtalas/core/autocmd.lua
lua/tpAtalas/core/options.lua

The new auto-highlight of the current word now disables the highlight whenever the cursor is moved in normal/insert mode. The updatetime is now configurable within the function of autocmd.

feat: Added the improved autocmd to auto highlight current word

---

lua/tpAtalas/core/keymaps.lua
lua/tpAtalas/plugins/lsp/lspconfig.lua

The custom function to organize imports is added to improve the organizing imports within the typescript file. The keymap for the organize imports is same as before: `<leader>fmo`.

feat: Added the custom `OrganizeImports` for typescript

---

lua/tpAtalas/plugins-setup.lua
lua/tpAtalas/plugins/comment.lua
lua/tpAtalas/plugins/treesitter.lua

Installed the new plugin: `nvim-ts-context-commentring` to support commenting on jsx/tsx. The commenting plugin `comment.nvim` does not support jsx/tsx.

feat: Added the comment support on jsx/tsx

---

lua/tpAtalas/core/autocmd.lua
lua/tpAtalas/plugins/lsp/null-ls.lua

`tsc`, offered by null-ls, caused the performance issue when the usage is combined with `auto-save`. The `auto-save` was previously set to save whenever the textChanged or exited the insertMode. This triggers the `tsc` to compile and send diagnostics at the workspace level every time code has been updated or changed. Increasing the debounce rate and changing the save method fixed the performance issues.
It is still necessary to improve the `tsc` checking method in the near future.

perf: Improved the performance caused by `tsc`

---

lua/user/plugins/lsp/null-ls.lua

As `tsc` diagnostics has been fixed that previously has memory leak issues, It is not set to on in `null-ls ` setting. `tsc` diagnostics gives workspace diagnostics within typescript files.

feat: Updated the `diagnostics.tsc` in `null-ls`

---

lua/user/plugins/lualine.lua

The number of the diagnostics are shown more than it should be on the `lualine`.
Example. One error occurs and number of diagnostics shown is 3 on the `lualine`.

fix: Fixed the issues with diagnostics in `lualine`

---

lua/user/core/colorscheme.lua

Updated the `custom. highlight` color to brighter color to be more distinctive and removed the font color of `MatchParen` to view the the default color of the font when highlighted.

feat: Updated the highlight color for a more distinctive color

---

.gitignore
lua/user/core/autocmd.lua
lua/user/plugins-setup.lua
lua/user/plugins/lsp/lspconfig.lua
lua/user/plugins/lsp/null-ls.lua
lua/user/plugins/lualine.lua
lua/user/plugins/nvim-tree.lua

Installed the new plugin called `ltex-extra` to improve the usability of `ltex` lsp. Currently, `ltex` has a feature to create custom path for the dictionary. If the custom path is found, It will use the custom path. If custom path is not found, the cwd is taken and dictionary will be created within the root level. This can lead us to manage all dictionaries, and other ltex's related files in a single place.
Other minor changes:
1. Refactored the cspell in `null-ls`
2. Add the autocmd to reload ltex dictionary files on saving (or BufWritePost)
3. Changed the `ltex` and `null-ls`'s cspell diagnostics severity to HINT
4. Added the `.gitignore`

feat: Added the `ltex` language tool

---

lua/user/plugins/lualine.lua

Added the missing sources from `lualine`. These sources were removed due to the fact that some sources generate duplicate diagnostics.
Further observation will be taken on the sources of diagnostics in lualine.

fix: Fixed the diagnostic issue on `lualine`

---

lua/user/plugins/lsp/lspconfig.lua

Removed the option from the typescript server to fix the issue that some diagnostic does not show up upon error.

fix: Fixed the typescript issue on diagnostic

---

README.md
lua/user/core/keymaps.lua
lua/user/plugins-setup.lua
lua/user/plugins/lsp/lspconfig.lua

Removed keymaps related to `typescript.nvim` as the plugin is removed, and replaced the `typescript.nvim` with `tsserver` from lspconfig.
Disabled the `CommonJS module` related diagnostics from `tsserver` as it is not necessary diagnostics to show in JavaScript file.

Feat: Removed the `typescript.nvim` and disabled specific diagnostic

---

lua/user/plugins/lsp/lspconfig.lua
lua/user/plugins/lsp/null-ls.lua
lua/user/plugins/lualine.lua

Removed the duplication sources from `lualine`, and removed the sign and section of `hint` from `lualine`, `null-ls`, and `lspconfig`.

refactor: Refactored the diagnostics

---

lua/user/core/autocmd.lua
lua/user/plugins/lsp/null-ls.lua

Removed the `cspell` from `null-ls` due to the high CPU usage. The cspell's spell checks cause the performance issues. As a replacement, the `codespell` is added to `null-ls`. Set the false on the `update_in_insert`, which was set to true initially.

feat: Minor Optimization

---

lua/user/core/autocmd.lua

Revert to CursorHold for auto-save as CursorHold gives the better user-experience.

feat: Changed the auto-save to CursorHold

---

lua/user/plugins/lspconfig.lua
lua/user/plugins/lspsaga.lua

After new update, lspsaga continuously causes the unknown error and that seems caused by enabling SymbolWinbar manually. Removing setting from the config of lspsaga fixed the issue.

fix: Fixed the `lspsaga`'s unknown error

---

init.lua
lazy-lock.json
lua/user/core/keymaps.lua
lua/user/plugins/init.lua

add `vim-hardtime` plugin to enable hardtime mode. The hardtime mode enables the limitation of using some keys, such as arrow keys. The configs are also added to `init.lua`, and the `hardtime_default_on` is commented in default.
Core changes:
- feat: add `vim-hardtime` plugin
- feat: add configs of `vim-hardtime`
Misc Changes:
- feat: disable the `F1` keys to open the help buffer.

feat: add new plugin

---

lua/user/core/autocmd.lua

The search function created in the previous commit is continuously shown on the `lualine`. To improve the user's experience, the last search register is cleared with an `autocmd` on BufUnload.

feat: add `autocmd` to clear the search on BufUnload

---

lua/user/plugins/null-ls.lua

As default spelling check option is set, the cspell diagnostics and codeactions are removed from the `null-ls`.

feat: remove the cspell from the null-ls

---

lua/user/core/keymaps.lua
lua/user/plugins/comment.lua

Update the keymaps for the spelling checks and update, and now commenting keymap is `?`, which include the line and block comment.

refactor: refactor the keymaps for spelling and commenting

---

lua/user/plugins/lspconfig.lua
lua/user/plugins/null-ls.lua

This commit reintroduces the cspell diagnostics and codeactions to the null-ls plugin, which had previously been removed. Additionally, the marksman LSP from lspconfig has been added to enable cspell support within markdown files.

feat: add cspell support to null-ls

---

lua/user/plugins/lspsaga.lua

The lightbulb is an option in `lspsaga` that displays a lightbulb icon where `codeaction` is possible. However, this feature can be distracting while writing, so the option has been set to `false`.

feat: disable the lightbulb from `lspsaga`

---

lua/user/core/keymaps.lua

Enhance the keymap for closing all buffers, preserving the current one and returning to the original position after the operation.

feat: update keymap for closing all buffers except current one

---

lua/user/plugins/lualine.lua

Remove the default tabline from lualine and leverage Harpoon's enhanced navigation capabilities.

feat: remove the tabline from the lualine

---

lua/user/keymaps.lua

Reintroduce the `preview=true` flag to the telescope, thereby enabling its preview feature. This functionality had previously been disabled.

feat: Enable preview functionality to Telescope

---

lua/user/plugins/lspconfig.lua

Replace the initially utilized typescript.nvim with typescript-tool.nvim, which enhances the tsserver response through direct interaction with the native Tsserver communication protocol.
This replacement results in more efficient and reliable communication with the Tsserver, facilitating improved TypeScript support and performance in the development environment.

feat: Substitute typescript.nvim with typescript-tool.nvim

---

lua/user/keymaps.lua

The typescript.nvim command keymaps have been replaced by typescript.tool keymaps, streamlining and updating the keymap set. It’s worth noting that the plugin currently lacks support for the command responsible for adding missing imports, which is compatible with typescript.tool.

feat: Replace typescript.nvim Keymaps with typescript.tool

---

lua/user/plugins/lspconfig.lua

An unused custom command, previously created for organizing the imported module within lspconfig, has been removed. The elimination contributes to a cleaner and more streamlined lspconfig.

refactor: Streamline lspconfig by removing unused  command

---

lua/user/plugins/lspconfig.lua

Update the condition for typescript-tools instead of tsserver to suppress the message. Enhancing the accuracy and relevance of diagnostics reporting.

refactor: Refine suppressing diagnostics message condition

---

lua/user/plugins/lualine.lua

Implement total_lines_project in the statusline to display the total line count of the current project, excluding files specified in .gitignore, reflecting only the lines tracked by git.
Refine icons for a more uniform and visually appealing presentation.

feat: Enhance statusline and improved icons

---

lua/user/plugins/lualine.lua

Remove the function to calculate the total lines of the projects in lualine due to performance reason.

refactor: Remove the calculating total lines of projects

---

lua/user/plugins/flash.lua

Remove the key options on the flash.nvim as search function can replace the key options.

refactor: Update the options of flash.nvim

---

lazy-lock.json
lua/keymaps.lua
lua/plugins/lspconfig.lua

Reverting to Typescript.nvim from Typescript-tool.nvim due to the latter's lack of diagnostic integration. Typescript-tool.nvim has been observed to cause unresponsiveness or significantly slow responses in diagnostics.
Note: Once Typescript-tool integrates with global diagnostics it will be a great idea to test again.

feat: Revert to Typescript.nvim for diagnostic integration

---

lua/keymaps.lua

Reinstate the previously omitted keymap for searching and replacing words under the cursor, ensuring compatibility with flash.nvim.
The new keymap implementation retains the original `<leader>rr` binding to search for words under the cursor. Recursive removal functionality via `cgn` is deliberately excluded to streamline keymapping usage, as the same can be triggered by directly typing `cgn`. The updated keymap promotes efficient interaction with the word search feature.

feat: Implement keymap for word search under cursor

---

lua/plugins/lspconfig.lua

Switch the condition to `tsserver` that was previously set to `typescript-tools`.

fix: Fix the commonJS diagnostic message

---

lua/keymaps.lua

Unused keymaps, which have been identified as redundant or non-beneficial in practical scenarios, are removed for a leaner configuration. Additional keymaps are integrated to facilitate efficient navigation between brackets.

refactor: Clean up unused keymaps, add bracket navigation

---

lua/keymaps.lua

Incorporate a new keymap that disables the search highlight once a search operation concludes. This enhancement ensures visibility of all search results within the viewport, but also allows for swift deactivation of highlighting, which can be distracting. Pressing the ESC key will now effectively disable the current search highlighting.

feat: Add keymap to disable search highlight

---

lua/keymaps.lua
lua/plugins/neo-tree.lua

Relocate keymaps associated with the Neotree plugin to the `Neotree` plugin file from the `keymaps` file. Enhances maintainability and organization.

refactor: Migrate Neotree keymaps

---

lua/keymaps.lua
lua/plugins/lspconfig.lua

Move the Lspconfig keymaps to the `lspconfig` file from the `keymaps` file to streamline the configuration structure.

feat: Relocate Lspconfig keymaps

---

lua/keymaps.lua
lua/plugins/init.lua
lua/plugins/markdown-preview.lua

Move Markdown-preview plugin to a dedicated plugin file and reposition its associated keymaps within the same file. Enhance structure and cohesiveness by keeping the plugin and its keymaps together.

refactor: Relocate Markdown-preview plugin and keymaps

---

lua/keymaps.lua
lua/plugins/harpoon.lua
lua/plugins/init.lua
lua/plugins/nvim-colorizer.lua
lua/plugins/vim-markdown-toc.lua

Create dedicated files for `vim-markdown-toc`, `vim-table-mode`, and `harpoon` plugins, ensuring associated keymaps reside within their respective plugin files, streamlining organization and readability.

refactor: Consolidate plugins and keymaps into dedicated files

---

lua/plugins/telescope.lua

Telescope's keymaps have been updated to begin with the letter `s` rather than `t`. This change applies to all derived keymaps.

feat: Update keymaps prefix in Telescope

---

lua/keymaps.lua
lua/plugins/toggle-term.lua

toggleTerm's keymaps now start with `a` instead of `t`. Superfluous comments within the global `keymap` have been removed.

refactor: Remap keymaps for toggle-term

---

lua/keymaps.lua
lua/plugins/lspconfig.lua
lua/plugins/treesitter.lua
lua/plugins/typescript.lua

Typescript plugin shifted to dedicated plugin file from Lspconfig, associated keys also relocated. Augments maintainability of overarching config.

refactor: Enhance Typescript plugin

---

.github/workflows/cleanup-workflow-runs.yml

The current update of workflow will run cron job every 90 days to only retain 20 days of workflow runs.

feat: Add the new workflow to cleanup workflow runs

---

.github/workflows/cleanup-workflow-runs.yml

The current update of workflow will run cron job every 90 days to only retain 20 days of workflow runs.

feat: Add the new workflow to cleanup workflow runs (#333)

---

lua/plugins/null-ls.lua

Remove deprecated and unused configurations in null-ls. Configure debounce settings and set update_in_insert to false to enhance performance.

refactor: Update null-ls configurations

---

lua/autocmd.lua

Adjust the colorcolumn setting for gitcommit within autocmd to 50, enhancing visual guidelines for commit message length.

refactor: Modify gitcommit colorcolumn setting

---

lua/lazy.lua

Add the `rounded` to the border of the Lazy.nvim to show the border of the Lazy UI.

feat: Update the UI to the Lazy.nvim

---

lua/keymaps.lua

Alterations to custom keymaps involve exchanging + with <End> and - with <Home>, deviating from the default settings. The impetus for such a change stems from the keyboard layout. Impact on general Neovim navigation should be minimal due to these keymap modifications.

refactor: Update custom keymaps

---

lazy-lock.json
lua/autocmd.lua

Add an autocmd to register the buffer into Harpoon before leaving Neovim, with a conditional check to avoid execution when leaving an empty buffer. Additionally, add an autocmd to clear jump history when entering Neovim, preventing unwanted jumping.

feat: Add the two new autocmds

---

lua/autocmd.lua

Modify the auto register function with autocmd to bypass files that match with .git and filetype gitcommit, ensuring specific file handling in the codebase.

feat: Enhance auto register condition for Harpoon

---

lua/plugins/lualine/init.lua

Set the event to VeryLazy for lualine loading with lazynvim. Move the custom component path_winbar to winbar section from tabline section.

refactor: Adjust Lualine configurations

---

lua/plugins/lualine/custom_components.lua
lua/plugins/lualine/init.lua

Remove the custom component called filename_with_icon, and restructure the lualine sections. Now file path will be shown on the statusline.

feat: Update the lualine configs

---

lua/plugins/telescope/init.lua
lua/plugins/telescope/keymaps.lua

Add the telescope-file-extension as the replacement of the oil.nvim and update its configs.

feat: Install and update telescope-file-extension

---

lazy-lock.json
lua/plugins/lspconfig/servers.lua
lua/plugins/typescript_nvim/init.lua

Reinstalled archived Typescript.nvim plugin due to its unique support for global diagnostics. While Typescript-tools serves as an alternative, it lacks current support for this feature. Typescript.nvim to act as interim solution until workspace diagnostics receive proper support.

feat: Reinstall archived Typescript.nvim plugin

---

lua/plugins/harpoon/autocmd.lua
lua/plugins/harpoon/init.lua

Add the custom autocmd for harpoon to add the buffer to harpoon before leaving the Vim. This enables the possbility to replace the autosession related plugin.

feat: Add the custom harpoon autocmd

---

lua/plugins/harpoon/autocmd.lua
lua/plugins/harpoon/init.lua

Harpoon's autocmd, when activated, now clears all previously saved files and saves the last session.

refactor: Refactor Harpoon's autocmd mechanism

---

lazy-lock.json
lua/plugins/tsc/init.lua

There is a conflict between watch mode and autocmd. Currently autocmd has been removed.

feat: Remove autocmd to autostart TSC
